version: '3.9'

services:
   postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-lmsdb}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-superPass}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
