FROM postgres:latest

ARG POSTGRES_DB=lmsdb
ARG POSTGRES_USER=postgres
ARG POSTGRES_PASSWORD=superPass

ENV POSTGRES_DB=$POSTGRES_DB
ENV POSTGRES_USER=$POSTGRES_USER
ENV POSTGRES_PASSWORD=$POSTGRES_PASSWORD

EXPOSE 5432
